### ISSUE TITLE
Conflict with bootstrap

### ISSUE THREAD

**Issue by lalarsson** [nnattawat/flip#12]
I've been trying to use Bootstrap together with Flip for a more flashy responsive experience but I've noticed that Bootrapped elements stop updating when the Flip-script runs. 

Is there any workaround or solution to this?

**Comment by nnattawat** [comment]
Can you give me more info about your problem? I use bootstrap on the demo page as well but did not use any JS component.

**Comment by sanrooney** [comment]
Hi,
You have done a great job. I have used this plugin in my projects. Now im developing a website
using Bootstrap, seems have some compatibility issue with Bootstrap.
before applying flip : http://rekareki.com/fazley_yaakob/
after applying flip : http://rekareki.com/test_flip/

It seems the problem is caused by setting card item to "absolute".
Any idea?

Thank you.

**Comment by nnattawat** [comment]
Yes, absolute position is required for flipping the content. So you can't put the flip content immediately after the col-x-4.

The quick fix would be style the grid yourself. Have a look at Grid example. (https://github.com/nnattawat/flip/blob/master/demo/index2.html)

**Comment by Download** [comment]
Answered sufficiently I think. Please re-open if you still have issues.
