### ISSUE TITLE
Feature request: 'random' value for axis

### ISSUE THREAD

**Issue by Seb33300** [nnattawat/flip#32]
I think it could be interesting to add value 'random' for the axis param.
So blocks will flip randomly on x or y axis.

**Comment by Download** [comment]
Mmmm I'm not sure... Now we want to change `axis` randomly, next it will be some pattern, or changing the `reverse` parameter... Where does it end?

Maybe it would be a better idea to fire a 'onflip' event or something? That way the client of the library can attach an event handler that changes whatever he wants to change after the flip:
```javascript
$('#card').flip().on('flip', function(evt){
  var newAxis;
  // determine new axis randomly or whatever...
  $(this).flip({axis: newAxis});
});

**Comment by JemarJones** [comment]
I agree that a feature like this doesn't really belong in flip. 

I like your idea @Download, though I think it might make the most sense to create a custom jquery event that anyone can use in the normal jquery way?

**Comment by Download** [comment]
Yes, i agree. A custom jQuery event would be the way to go. I have no experience with it however and (atm) no time to work on it...

**Comment by JemarJones** [comment]
I also have no experience with it, but I've enough time so Ill give it a go. 

In your example the function is the function meant to be called on complete? This makes the most sense but I think @Seb33300 would need it to be called before each flip took place. Which would be a little messy to implement just because changing the axis is async itself 

I think all that needs to be done is determining the new axis and setting it. This is a client side concern though.

Still, I'm interested in the sort of persistent callback idea so I'll try to work on that.

**Comment by Download** [comment]
@JemarJones  Yes I think you are right. Most beatiful solution would probably be if you could do things like `event.preventDefault();` to cancel the flip etc.

**Comment by JemarJones** [comment]
jQuery events added in https://github.com/nnattawat/flip/releases/tag/v1.0.14

@Seb33300 I apologize for the highjacking of your issue! Unfortunately i believe its generally agreed upon that your suggestion doesn't quite belong in flip, but can be done with client code rather easily!

Closing now.
